version: "3"

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    networks:
      - node-network
    tty: true
    depends_on:
      - node

  node:
    build:
      context: node
    container_name: node
    entrypoint: sh -c "npm install && npm run dev"
    volumes:
      - ./node:/usr/src/app
      # - /usr/src/app/node_modules # volume anonimo (link simbolico)
    networks:
      - node-network
    tty: true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  node-network:
    driver: bridge